# fly.toml app configuration file generated for aged-bird-9423 on 2023-04-25T03:04:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-bird-9423"
primary_region = "nrt"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_URL = " https://aged-bird-9423.fly.dev"
  APP_NAME ="tasklist"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.kaapqbvzfnbuxtixfwtw.supabase.co"
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"
  

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
